// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateImplement.Models;

#nullable disable

namespace TemplateImplement.Migrations
{
    [DbContext(typeof(TemplateContext))]
    [Migration("20251109164055_ProductsMigration")]
    partial class ProductsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateImplement.Models.Products", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("prod_desc");

                    b.Property<string>("Image")
                        .HasColumnType("Varchar(300)")
                        .HasColumnName("prod_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("prod_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("prod_price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("prod_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("tbl_products");
                });
#pragma warning restore 612, 618
        }
    }
}
